name: Query Test
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Set Yarn Shell
        run: yarn config set script-shell bash
      - name: Get Latest Block
        # This will determine the latest block and write it to a file
        # The same output will then be set to an environment variable for use in the next step
        run: |
          yarn query:latest-block
      - name: Evaluate Latest Block
        run: |
          export LATEST_BLOCK=$(cat query-test/block.txt)
          echo "LATEST_BLOCK=$LATEST_BLOCK" >> $GITHUB_ENV
      - name: Upload Latest Block
        uses: actions/upload-artifact@v3
        with:
          name: latest-block
          path: query-test/block.txt
      - name: Get Token Records
        run: |
          yarn query:test ${{ env.LATEST_BLOCK }}
      - name: Upload Token Records
        uses: actions/upload-artifact@v3
        with:
          name: token-records-branch
          path: query-test/records.json
  test-base:
    runs-on: ubuntu-latest
    needs: [test-branch]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }}
      - name: Set Yarn Shell
        run: yarn config set script-shell bash
      - name: Download Latest Block
        uses: actions/download-artifact@v3
        with:
          name: latest-block
      - name: Evaluate Latest Block
        run: |
          export LATEST_BLOCK=$(cat block.txt)
          echo "LATEST_BLOCK=$LATEST_BLOCK" >> $GITHUB_ENV
      - name: Get Token Records
        run: |
          yarn query:test ${{ env.LATEST_BLOCK }}
      - name: Upload Token Records
        uses: actions/upload-artifact@v3
        with:
          name: token-records-base
          path: query-test/records.json
  compare:
    runs-on: ubuntu-latest
    needs: [test-branch, test-base]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Set Yarn Shell
        run: yarn config set script-shell bash
      - name: Token Records Base
        uses: actions/download-artifact@v3
        with:
          name: token-records-base
      - name: Rename Token Records Base
        run: mv records.json records-base.json
      - name: Token Records Branch
        uses: actions/download-artifact@v3
        with:
          name: token-records-branch
      - name: Rename Token Records Branch
        run: mv records.json records-branch.json
      - name: Compare Token Records
        # Upstream path as the command is run in the query-test/ directory
        run: |
          yarn query:compare ../records-base.json ../records-branch.json
      - name: Determine Result
        id: result
        run: |
          echo "::set-output name=result::$(jq .marketValue.result query-test/comparison.json)"
          echo "::set-output name=marketValue-base::$(jq .marketValue.base query-test/comparison.json)"
          echo "::set-output name=marketValue-branch::$(jq .marketValue.branch query-test/comparison.json)"
          echo "::set-output name=diff::$(diff <(jq --sort-keys . records-base.json) <(jq --sort-keys . records-branch.json))"
      - name: Post Comment - Success
        if: steps.result.outputs.result == 'true'
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Result: ✅
            Values were within threshold.

            Market Value:
             Base: ${{ steps.result.outputs.marketValue-base }}
             Branch: ${{ steps.result.outputs.marketValue-branch }}
      - name: Post Comment - Failure
        if: steps.result.outputs.result == 'false'
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Result: ❌
            Values were NOT within threshold.

            Market Value:
             Base: ${{ steps.result.outputs.marketValue-base }}
             Branch: ${{ steps.result.outputs.marketValue-branch }}

            Diff:
            ```diff
            ${{ steps.result.outputs.diff }}
            ```
